### ISSUE TITLE
t.getContext is not a function

### ISSUE THREAD

**Issue by lionsguard** [BlazorExtensions/Canvas#27]
I get the following exception attempting to use the canvas:
```
Exception thrown: 'Microsoft.JSInterop.JSException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer: Warning: Unhandled exception rendering component: t.getContext is not a function
TypeError: t.getContext is not a function
    at add (https://localhost:44387/js/blazor.extensions.canvas.js:1:1738)
    at https://localhost:44387/_framework/blazor.server.js:8:21434
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44387/_framework/blazor.server.js:8:21403)
    at https://localhost:44387/_framework/blazor.server.js:1:16653
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44387/_framework/blazor.server.js:1:16624)
    at e.processIncomingData (https://localhost:44387/_framework/blazor.server.js:1:14624)
    at e.connection.onreceive (https://localhost:44387/_framework/blazor.server.js:1:11165)
    at WebSocket.i.onmessage (https://localhost:44387/_framework/blazor.server.js:1:30454)
```

This is the component class using it:
```
public class Map : ComponentBase
    {
        [Inject]
        protected IJSRuntime JsRuntime { get; set; }

        [Parameter]
        public long Width { get; set; } = 300;

        [Parameter]
        public long Height { get; set; } = 300;

        BECanvas canvas;
        Canvas2DContext context;

        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);

            var index = 0;

            builder.OpenComponent<BECanvas>(index++);
            builder.AddAttribute(index++, "width", Width);
            builder.AddAttribute(index++, "height", Height);
            builder.AddComponentReferenceCapture(index++, o => canvas = (BECanvas)o);
            builder.CloseComponent();
        }

        protected override async Task OnAfterRenderAsync()
        {
            await base.OnAfterRenderAsync();

            context = await canvas.CreateCanvas2DAsync();

            await context.SetFillStyleAsync("red");
            await context.FillRectAsync(0, 0, Width, Height);
        }
    }
```

Not sure what I am missing. I've included the JS file in the head of the _Host doc. The canvas is rendered as follows:
`<canvas id="8f95bf4c-0fce-4d0c-9250-39e04b07a5b9" width="1900" height="949" ref="_canvasRef"></canvas>`

**Comment by galvesribeiro** [comment]
Hello!

I believe this is because this package wasn't upgraded to preview6 _yet_.

Will try do it soon.

Thank you for the report!

**Comment by chucker** [comment]
@lionsguard have you tried again with 0.2?
